export const DEFAULT_USER_ID = 1;

export const SPECIES_POOL = ['Cat', 'Dog', 'Rabbit', 'Fox', 'Dragon', 'Phoenix'];

export const RARITY_NAMES: Record<number, string> = {
  1: '普通 Common',
  2: '优秀 Uncommon',
  3: '稀有 Rare',
  4: '史诗 Epic',
  5: '传说 Legendary',
  6: '神话 Mythic',
};

export const STAT_RANGES: Record<
  number,
  {
    hp: [number, number];
    attack: [number, number];
    defense: [number, number];
    speed: [number, number];
  }
> = {
  1: { hp: [100, 130], attack: [15, 25], defense: [8, 15], speed: [8, 15] },
  2: { hp: [130, 170], attack: [25, 35], defense: [15, 25], speed: [15, 25] },
  3: { hp: [170, 230], attack: [35, 50], defense: [25, 35], speed: [25, 35] },
  4: { hp: [230, 320], attack: [50, 70], defense: [35, 50], speed: [35, 50] },
  5: { hp: [320, 450], attack: [70, 100], defense: [50, 75], speed: [50, 75] },
  6: { hp: [450, 650], attack: [100, 150], defense: [75, 120], speed: [75, 120] },
};

export const DEFAULT_ITEMS = [
  {
    itemCode: 'apple',
    name: '苹果',
    description: '食物，饥饿 +20',
    type: 'food',
    rarity: 1,
    maxStack: 999,
    usable: true,
    effect: 'hunger',
    effectValue: 20,
  },
  {
    itemCode: 'dried_fish',
    name: '小鱼干',
    description: '食物，快乐 +20',
    type: 'food',
    rarity: 1,
    maxStack: 999,
    usable: true,
    effect: 'happiness',
    effectValue: 20,
  },
  {
    itemCode: 'clean_spray',
    name: '清洁喷雾',
    description: '清洁道具，清洁 +20',
    type: 'clean',
    rarity: 1,
    maxStack: 999,
    usable: true,
    effect: 'cleanliness',
    effectValue: 20,
  },
  {
    itemCode: 'exp_potion_small',
    name: '初级经验药水',
    description: '经验 +50',
    type: 'potion',
    rarity: 1,
    maxStack: 999,
    usable: true,
    effect: 'exp',
    effectValue: 50,
  },
  {
    itemCode: 'exp_potion_medium',
    name: '中级经验药水',
    description: '经验 +150',
    type: 'potion',
    rarity: 2,
    maxStack: 999,
    usable: true,
    effect: 'exp',
    effectValue: 150,
  },
  {
    itemCode: 'exp_potion_large',
    name: '高级经验药水',
    description: '经验 +500',
    type: 'potion',
    rarity: 3,
    maxStack: 999,
    usable: true,
    effect: 'exp',
    effectValue: 500,
  },
  {
    itemCode: 'common_pet_egg',
    name: '普通宠物蛋',
    description: '使用后进入孵化列表',
    type: 'egg',
    rarity: 1,
    maxStack: 99,
    usable: true,
    effect: 'egg',
    effectValue: 1,
  },
  {
    itemCode: 'rare_pet_egg',
    name: '稀有宠物蛋',
    description: '使用后进入孵化列表',
    type: 'egg',
    rarity: 3,
    maxStack: 99,
    usable: true,
    effect: 'egg',
    effectValue: 3,
  },
];

export const DEFAULT_SHOP_ITEMS = [
  { itemCode: 'apple', currencyType: 'gold', price: 50, quantity: 1 },
  { itemCode: 'dried_fish', currencyType: 'gold', price: 120, quantity: 1 },
  { itemCode: 'clean_spray', currencyType: 'gold', price: 80, quantity: 1 },
  { itemCode: 'exp_potion_small', currencyType: 'gold', price: 100, quantity: 1 },
  { itemCode: 'exp_potion_medium', currencyType: 'gold', price: 300, quantity: 1 },
  { itemCode: 'exp_potion_large', currencyType: 'diamond', price: 10, quantity: 1 },
  { itemCode: 'common_pet_egg', currencyType: 'gold', price: 500, quantity: 1 },
  { itemCode: 'rare_pet_egg', currencyType: 'diamond', price: 30, quantity: 1 },
];

export const DEFAULT_SKILLS = [
  {
    skillCode: 'claw_strike',
    name: '小爪击',
    description: '攻击技能，造成 20 额外伤害',
    rarity: 1,
    type: 'attack',
    power: 20,
    triggerRate: 0.35,
    effect: 'damage',
  },
  {
    skillCode: 'tough_fur',
    name: '坚韧皮毛',
    description: '被动，生命 +20',
    rarity: 1,
    type: 'passive',
    power: 20,
    triggerRate: 1,
    effect: 'hp+20',
  },
  {
    skillCode: 'quick_steps',
    name: '灵敏步伐',
    description: '被动，速度 +5',
    rarity: 1,
    type: 'passive',
    power: 5,
    triggerRate: 1,
    effect: 'speed+5',
  },
  {
    skillCode: 'pounce',
    name: '猛扑',
    description: '攻击技能，造成 40 额外伤害',
    rarity: 2,
    type: 'attack',
    power: 40,
    triggerRate: 0.3,
    effect: 'damage',
  },
  {
    skillCode: 'shield_instinct',
    name: '护盾本能',
    description: '被动，防御 +10',
    rarity: 2,
    type: 'passive',
    power: 10,
    triggerRate: 1,
    effect: 'defense+10',
  },
  {
    skillCode: 'happy_recovery',
    name: '快乐恢复',
    description: '战斗后恢复少量生命',
    rarity: 2,
    type: 'heal',
    power: 20,
    triggerRate: 0.35,
    effect: 'post_heal',
  },
  {
    skillCode: 'combo',
    name: '连击',
    description: '攻击时 25% 概率追加一次攻击',
    rarity: 3,
    type: 'attack',
    power: 0,
    triggerRate: 0.25,
    effect: 'combo',
  },
  {
    skillCode: 'life_drain',
    name: '生命汲取',
    description: '造成伤害时恢复 20% 伤害生命',
    rarity: 3,
    type: 'heal',
    power: 20,
    triggerRate: 0.35,
    effect: 'lifesteal',
  },
  {
    skillCode: 'critical_instinct',
    name: '暴击本能',
    description: '暴击率提升',
    rarity: 3,
    type: 'buff',
    power: 50,
    triggerRate: 0.2,
    effect: 'critical',
  },
  {
    skillCode: 'flame_impact',
    name: '烈焰冲击',
    description: '高伤害攻击，power 90',
    rarity: 4,
    type: 'attack',
    power: 90,
    triggerRate: 0.28,
    effect: 'damage',
  },
  {
    skillCode: 'godspeed',
    name: '神速',
    description: '被动，速度 +30',
    rarity: 4,
    type: 'passive',
    power: 30,
    triggerRate: 1,
    effect: 'speed+30',
  },
  {
    skillCode: 'battle_rage',
    name: '战斗怒意',
    description: '血量低于 30% 时 attack +30%',
    rarity: 4,
    type: 'buff',
    power: 30,
    triggerRate: 1,
    effect: 'low_hp_attack',
  },
  {
    skillCode: 'dragon_breath',
    name: '龙息',
    description: '超高伤害，power 140',
    rarity: 5,
    type: 'attack',
    power: 140,
    triggerRate: 0.25,
    effect: 'damage',
  },
  {
    skillCode: 'unyielding_will',
    name: '不屈意志',
    description: '死亡时 20% 概率保留 1 HP',
    rarity: 5,
    type: 'passive',
    power: 20,
    triggerRate: 0.2,
    effect: 'survive_one',
  },
  {
    skillCode: 'royal_pressure',
    name: '王者威压',
    description: '降低敌方攻击',
    rarity: 5,
    type: 'debuff',
    power: 15,
    triggerRate: 1,
    effect: 'enemy_attack_down',
  },
  {
    skillCode: 'phoenix_rebirth',
    name: '凤凰涅槃',
    description: '死亡后复活一次，恢复 30% HP',
    rarity: 6,
    type: 'passive',
    power: 30,
    triggerRate: 1,
    effect: 'rebirth',
  },
  {
    skillCode: 'star_judgement',
    name: '星辰审判',
    description: '高伤害并无视部分防御',
    rarity: 6,
    type: 'attack',
    power: 160,
    triggerRate: 0.22,
    effect: 'ignore_defense',
  },
  {
    skillCode: 'divine_guard',
    name: '神域庇护',
    description: '受到伤害降低 25%',
    rarity: 6,
    type: 'passive',
    power: 25,
    triggerRate: 1,
    effect: 'damage_reduce',
  },
];
