export type SkillTier = 'low' | 'high' | 'special';

export interface SkillSeedConfig {
  skillCode: string;
  familyCode: string;
  name: string;
  description: string;
  rarity: number;
  tier: SkillTier;
  type: string;
  category: string;
  power: number;
  triggerRate: number;
  effect: string;
  effectData: Record<string, any>;
  triggerLimit: Record<string, number>;
  conflictGroup: string;
  roleAffinity: string[];
  inheritanceWeight: number;
  canPurchase: boolean;
  canLock: boolean;
  canOverwrite: boolean;
  canInherit: boolean;
  speciesCode: string;
  enabled: boolean;
  version: string;
}

export const SKILL_CONFIG_VERSION = '2.0.0';

const pair = (
  suffix: string,
  lowName: string,
  highName: string,
  category: string,
  type: string,
  effect: string,
  lowPower: number,
  lowRate: number,
  lowData: Record<string, any>,
  highPower: number,
  highRate: number,
  highData: Record<string, any>,
): SkillSeedConfig[] => {
  const familyCode = `FAMILY_${suffix}`;
  const conflictGroup =
    suffix === 'SPEED_UP' || suffix === 'SLOW_TANK' ? 'speed_stance' :
    suffix === 'DEATH_SAVE' ? 'death_prevention' :
    '';

  return [
    {
      skillCode: `LOW_${suffix}`,
      familyCode,
      name: lowName,
      description: lowName,
      rarity: 1,
      tier: 'low',
      type,
      category,
      power: lowPower,
      triggerRate: lowRate,
      effect,
      effectData: lowData,
      triggerLimit: {},
      conflictGroup,
      roleAffinity: [category],
      inheritanceWeight: 1,
      canPurchase: true,
      canLock: true,
      canOverwrite: true,
      canInherit: true,
      speciesCode: '',
      enabled: true,
      version: SKILL_CONFIG_VERSION,
    },
    {
      skillCode: `HIGH_${suffix}`,
      familyCode,
      name: highName,
      description: highName,
      rarity: 4,
      tier: 'high',
      type,
      category,
      power: highPower,
      triggerRate: highRate,
      effect,
      effectData: highData,
      triggerLimit: {},
      conflictGroup,
      roleAffinity: [category],
      inheritanceWeight: 0.55,
      canPurchase: true,
      canLock: true,
      canOverwrite: true,
      canInherit: true,
      speciesCode: '',
      enabled: true,
      version: SKILL_CONFIG_VERSION,
    },
  ];
};

export const NORMAL_SKILL_CONFIGS: SkillSeedConfig[] = [

  ...pair('PHYSICAL_COMBO', '连击', '高级连击', 'physical', 'trigger', 'physical_combo', 45, 0.2, {"extraDamageRate":0.45,"maxPerTurn":1}, 55, 0.35, {"extraDamageRate":0.55,"maxPerTurn":1}),
  ...pair('PHYSICAL_CRIT', '必杀', '高级必杀', 'physical', 'passive', 'physical_crit', 8, 1, {"critRateBonus":0.08,"critDamageBonus":0.1}, 15, 1, {"critRateBonus":0.15,"critDamageBonus":0.2}),
  ...pair('PHYSICAL_POWER', '强力', '高级强力', 'physical', 'passive', 'physical_power', 8, 1, {"physicalDamageBonus":0.08}, 15, 1, {"physicalDamageBonus":0.15}),
  ...pair('AMBUSH', '偷袭', '高级偷袭', 'physical', 'trigger', 'ambush', 12, 1, {"firstDamageBonus":0.12,"defenseIgnore":0.08}, 20, 1, {"firstDamageBonus":0.2,"defenseIgnore":0.15}),
  ...pair('PURSUIT', '追击', '高级追击', 'physical', 'trigger', 'pursuit', 50, 0.2, {"hpThreshold":0.3,"extraDamageRate":0.5,"maxPerTurn":1}, 70, 0.35, {"hpThreshold":0.3,"extraDamageRate":0.7,"maxPerTurn":1}),
  ...pair('MAGIC_COMBO', '法术连击', '高级法术连击', 'magic', 'trigger', 'magic_combo', 40, 0.18, {"repeatEffectRate":0.4,"maxPerTurn":1}, 55, 0.3, {"repeatEffectRate":0.55,"maxPerTurn":1}),
  ...pair('MAGIC_CRIT', '法术暴击', '高级法术暴击', 'magic', 'passive', 'magic_crit', 8, 1, {"magicCritRateBonus":0.08}, 15, 1, {"magicCritRateBonus":0.15}),
  ...pair('MAGIC_VARIANCE', '法术波动', '高级法术波动', 'magic', 'passive', 'magic_variance', 115, 1, {"minRate":0.9,"maxRate":1.15}, 130, 1, {"minRate":0.85,"maxRate":1.3}),
  ...pair('MAGIC_POWER', '灵能', '高级灵能', 'magic', 'passive', 'magic_power', 8, 1, {"magicStatBonus":0.08}, 15, 1, {"magicStatBonus":0.15}),
  ...pair('MAGIC_PIERCE', '法术穿透', '高级法术穿透', 'magic', 'passive', 'magic_pierce', 8, 1, {"damageReductionIgnore":0.08}, 15, 1, {"damageReductionIgnore":0.15}),
  ...pair('PHYSICAL_GUARD', '防御', '高级防御', 'defense', 'passive', 'physical_guard', 7, 1, {"physicalDamageReduction":0.07}, 13, 1, {"physicalDamageReduction":0.13}),
  ...pair('MAGIC_GUARD', '固法', '高级固法', 'defense', 'passive', 'magic_guard', 7, 1, {"magicDamageReduction":0.07}, 13, 1, {"magicDamageReduction":0.13}),
  ...pair('PARRY', '招架', '高级招架', 'defense', 'trigger', 'parry', 30, 0.1, {"damageReduction":0.3,"maxPerTurn":1}, 40, 0.18, {"damageReduction":0.4,"maxPerTurn":1}),
  ...pair('REFLECT', '反震', '高级反震', 'defense', 'trigger', 'reflect', 20, 0.15, {"reflectRate":0.2,"maxPerTurn":2}, 30, 0.25, {"reflectRate":0.3,"maxPerTurn":2}),
  ...pair('OPENING_SHIELD', '护盾', '高级护盾', 'defense', 'trigger', 'opening_shield', 8, 1, {"maxHpRate":0.08,"durationTurns":2}, 15, 1, {"maxHpRate":0.15,"durationTurns":2}),
  ...pair('MAX_HP', '强壮', '高级强壮', 'survival', 'passive', 'max_hp', 8, 1, {"maxHpBonus":0.08}, 15, 1, {"maxHpBonus":0.15}),
  ...pair('REGEN', '再生', '高级再生', 'survival', 'trigger', 'regen', 2.5, 1, {"maxHpRate":0.025,"maxPerTurn":1}, 4.5, 1, {"maxHpRate":0.045,"maxPerTurn":1}),
  ...pair('LIFESTEAL', '吸血', '高级吸血', 'survival', 'trigger', 'lifesteal', 8, 1, {"damageToHealRate":0.08}, 15, 1, {"damageToHealRate":0.15}),
  ...pair('DEATH_SAVE', '神佑', '高级神佑', 'survival', 'trigger', 'death_save', 8, 0.08, {"remainHp":1,"maxPerBattle":1}, 15, 0.15, {"remainHp":1,"maxPerBattle":1}),
  ...pair('LAST_STAND', '不屈', '高级不屈', 'survival', 'passive', 'last_stand', 10, 1, {"hpThreshold":0.3,"damageReduction":0.1}, 20, 1, {"hpThreshold":0.3,"damageReduction":0.2}),
  ...pair('SPEED_UP', '敏捷', '高级敏捷', 'speed', 'passive', 'speed_up', 8, 1, {"speedBonus":0.08}, 15, 1, {"speedBonus":0.15}),
  ...pair('SLOW_TANK', '迟缓', '高级迟缓', 'speed', 'passive', 'slow_tank', 4, 1, {"speedPenalty":0.08,"damageReduction":0.04}, 8, 1, {"speedPenalty":0.15,"damageReduction":0.08}),
  ...pair('ACCURACY', '精准', '高级精准', 'utility', 'passive', 'accuracy', 10, 1, {"accuracyBonus":0.1,"shieldDamageBonus":0.05}, 20, 1, {"accuracyBonus":0.2,"shieldDamageBonus":0.1}),
  ...pair('CONTROL_RESIST', '抗控', '高级抗控', 'utility', 'passive', 'control_resist', 10, 1, {"controlResistBonus":0.1}, 20, 1, {"controlResistBonus":0.2}),
  ...pair('DISPEL', '驱散', '高级驱散', 'utility', 'trigger', 'dispel_on_hit', 1, 0.1, {"removeBuffCount":1,"maxPerTurn":1}, 1, 0.2, {"removeBuffCount":1,"maxPerTurn":1}),
  ...pair('HEALING_POWER', '治愈', '高级治愈', 'support', 'passive', 'healing_power', 10, 1, {"healingAndShieldBonus":0.1}, 20, 1, {"healingAndShieldBonus":0.2}),
  ...pair('ENERGY_GAIN', '回能', '高级回能', 'support', 'trigger', 'energy_gain', 8, 1, {"energyPerTurn":8}, 15, 1, {"energyPerTurn":15}),
  ...pair('CLEANSE', '净化', '高级净化', 'support', 'trigger', 'cleanse', 1, 0.1, {"removeDebuffCount":1,"maxPerTurn":1}, 1, 0.2, {"removeDebuffCount":1,"maxPerTurn":1}),
  ...pair('GUARD_ALLY', '援护', '高级援护', 'support', 'trigger', 'guard_ally', 60, 0.12, {"allyHpThreshold":0.3,"takenDamageRate":0.6,"maxPerTurn":1}, 50, 0.22, {"allyHpThreshold":0.3,"takenDamageRate":0.5,"maxPerTurn":1}),
  ...pair('HEALING_ECHO', '复苏', '高级复苏', 'support', 'trigger', 'healing_echo', 3, 0.2, {"extraMaxHpHealRate":0.03,"maxPerTurn":1}, 5, 0.35, {"extraMaxHpHealRate":0.05,"maxPerTurn":1}),
];

export const SPECIAL_SKILL_CONFIGS: SkillSeedConfig[] = [
  {
    skillCode: 'SPECIAL_PET001',
    familyCode: 'FAMILY_SPECIAL_PET001',
    name: '焚心尾焰',
    description: '每回合首次法术命中附加焚印；友方再次伤害时爆炸。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.35,
    triggerRate: 1,
    effect: 'special_burning_mark',
    effectData: {"durationTurns":2,"magicDamageRate":0.35,"maxPerTargetPerTurn":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET001',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET002',
    familyCode: 'FAMILY_SPECIAL_PET002',
    name: '玄甲回响',
    description: '累计损失20%最大生命时为全队生成护盾。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.05,
    triggerRate: 1,
    effect: 'special_team_shield',
    effectData: {"lostHpStep":0.2,"shieldMaxHpRate":0.05,"maxPerTurn":1,"maxPerBattle":3},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET002',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET003',
    familyCode: 'FAMILY_SPECIAL_PET003',
    name: '时跃残影',
    description: '首次被单体锁定时推进自身行动条并大幅减伤。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.6,
    triggerRate: 1,
    effect: 'special_time_afterimage',
    effectData: {"actionBarForward":0.3,"damageReduction":0.6,"nextAttackBonus":0.3,"maxPerBattle":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET003',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET004',
    familyCode: 'FAMILY_SPECIAL_PET004',
    name: '月相祈愿',
    description: '回合结束治疗最低生命友方，危急时额外净化。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.06,
    triggerRate: 1,
    effect: 'special_moon_prayer',
    effectData: {"targetMaxHpRate":0.06,"magicRate":0.3,"criticalHpThreshold":0.3,"cooldownTurns":2},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET004',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET005',
    familyCode: 'FAMILY_SPECIAL_PET005',
    name: '雷霆蓄势',
    description: '直接攻击叠加雷势，三层后弹射两名敌人。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.45,
    triggerRate: 1,
    effect: 'special_thunder_charge',
    effectData: {"maxStacks":3,"bounceTargets":2,"bounceDamageRate":0.45},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET005',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET006',
    familyCode: 'FAMILY_SPECIAL_PET006',
    name: '潮汐逆流',
    description: '敌方首次获得额外行动或速度增益时削减行动条并治疗友方。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.2,
    triggerRate: 1,
    effect: 'special_tide_reversal',
    effectData: {"actionBarReduce":0.2,"allyMaxHpHealRate":0.04,"maxPerTurn":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET006',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET007',
    familyCode: 'FAMILY_SPECIAL_PET007',
    name: '暗影狩猎',
    description: '攻击残血目标时穿防，击杀后进入隐匿并回能。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.2,
    triggerRate: 1,
    effect: 'special_shadow_hunt',
    effectData: {"hpThreshold":0.35,"defenseIgnore":0.2,"energyGain":20,"maxPerTurn":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET007',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET008',
    familyCode: 'FAMILY_SPECIAL_PET008',
    name: '生命共鸣',
    description: '过量治疗的一部分转化为全队护盾。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.6,
    triggerRate: 1,
    effect: 'special_life_resonance',
    effectData: {"overhealToShieldRate":0.6,"turnCapMaxHpRate":0.08,"durationTurns":2},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET008',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET009',
    familyCode: 'FAMILY_SPECIAL_PET009',
    name: '星界共鸣',
    description: '全队每累计施放三次主动技能，按第三次技能类型获得团队增益。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.08,
    triggerRate: 1,
    effect: 'special_astral_resonance',
    effectData: {"skillCount":3,"damageBonus":0.08,"healingBonus":0.1,"damageReduction":0.08,"durationTurns":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET009',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
  {
    skillCode: 'SPECIAL_PET010',
    familyCode: 'FAMILY_SPECIAL_PET010',
    name: '霜封预言',
    description: '标记敌方最快单位，反复压制行动条并在三次后冻结。',
    rarity: 6,
    tier: 'special',
    type: 'trigger',
    category: 'special',
    power: 0.2,
    triggerRate: 1,
    effect: 'special_frost_prophecy',
    effectData: {"actionBarThreshold":0.8,"actionBarReduce":0.2,"triggerToFreeze":3,"freezeTurns":1},
    triggerLimit: {},
    conflictGroup: '',
    roleAffinity: ['special'],
    inheritanceWeight: 0,
    canPurchase: false,
    canLock: false,
    canOverwrite: true,
    canInherit: true,
    speciesCode: 'PET010',
    enabled: true,
    version: SKILL_CONFIG_VERSION,
  },
];

export const ALL_SKILL_CONFIGS: SkillSeedConfig[] = [
  ...NORMAL_SKILL_CONFIGS,
  ...SPECIAL_SKILL_CONFIGS,
];

const SKILL_MAP = new Map(ALL_SKILL_CONFIGS.map((skill) => [skill.skillCode, skill]));

export function getSkillSeedConfig(skillCode?: string | null) {
  return SKILL_MAP.get(String(skillCode || '')) || null;
}

export function getLowSkillConfigs() {
  return NORMAL_SKILL_CONFIGS.filter((skill) => skill.tier === 'low');
}

export function isSpecialSkill(skill: any) {
  if (!skill) return false;
  if (skill.tier === 'special') return true;
  return getSkillSeedConfig(skill.skillCode)?.tier === 'special';
}
