export const V6_CANVAS_WIDTH = 720;
export const V6_CANVAS_HEIGHT = 1280;

export const V6_TOP_BAR_HEIGHT = 112;
export const V6_BOTTOM_NAV_HEIGHT = 126;
export const V6_CONTENT_HEIGHT = V6_CANVAS_HEIGHT - V6_TOP_BAR_HEIGHT - V6_BOTTOM_NAV_HEIGHT;
export const V6_CONTENT_CENTER_Y = (V6_BOTTOM_NAV_HEIGHT - V6_TOP_BAR_HEIGHT) / 2;
export const V6_TOP_BAR_CENTER_Y = V6_CANVAS_HEIGHT / 2 - V6_TOP_BAR_HEIGHT / 2;
export const V6_BOTTOM_NAV_CENTER_Y = -V6_CANVAS_HEIGHT / 2 + V6_BOTTOM_NAV_HEIGHT / 2;

export const V6_SAFE_SIDE = 18;
export const V6_PANEL_GAP = 12;
export const V6_PAGE_WIDTH = V6_CANVAS_WIDTH - V6_SAFE_SIDE * 2;

